"""The one and only "payload" used anywhere in this project's corpus.

write_marker(name) appends a timestamped line to
evidence/markers/marker_log.txt under this project's own directory. That is
the entire effect. It proves the mechanism every real malicious pickle relies
on -- that unpickling can invoke an arbitrary callable via a GLOBAL + REDUCE
opcode pair -- without the callable doing anything harmful: no shell, no
network, no file access outside this project's own scratch directory.

Only this project's own corpus files, generated by
scripts/01_generate_corpus.py, ever reference this module. It is never
invoked directly except when this project's own tests or scanner runs choose
to unpickle a corpus file it authored, in a scratch directory, as documented
in README.md.
"""
from __future__ import annotations

import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
MARKER_DIR = PROJECT_ROOT / "evidence" / "markers"
MARKER_LOG = MARKER_DIR / "marker_log.txt"


def write_marker(name: str) -> str:
    """Append a timestamped line naming `name` to the marker log and return
    the line written. This is the full effect of every inert PoC payload in
    this corpus."""
    MARKER_DIR.mkdir(parents=True, exist_ok=True)
    line = f"{datetime.datetime.now(datetime.timezone.utc).isoformat()} marker={name}\n"
    with open(MARKER_LOG, "a") as f:
        f.write(line)
    return line
